<a href="https://colab.research.google.com/github/Sudharsan-ai/exno1/blob/main/assign.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
df = pd.read_csv("SAMPLEIDS.csv")
df

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,NaN,NaN,NaN
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,NaN,59.0,60.0,70.0,NaN,0.000000
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
9,9,1220129,INDRA,2000.09.21,FEMALE,KANCHIPURAM,64.0,NaN,NaN,64.0,NaN,0.000000
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,NaN,68.0,70.0,70.0,208.0,69.333333
13,13,1220133,MANI,2000-10-02,MALE,KANCHIPURAM,71.0,76.0,NaN,71.0,NaN,0.000000
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
15,15,1220135,NaN,19990125,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
17,17,1220137,RAGHU,20001109,MALE,POONAMALEE,67.0,64.0,70.0,NaN,201.0,67.000000
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,NaN,84.0,NaN,0.000000
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [6]:
df.shape

(21, 12)

In [7]:
df.head(2)

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,NaN,NaN,NaN
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333

In [8]:
df.tail(2)

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,NaN,84.0,NaN,0.000000
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [9]:
df.describe()

,SNO,REGNO,M1,M2,M3,M4,TOTAL,AVG
count,21.000000,2.100000e+01,18.000000,19.000000,17.000000,18.000000,16.000000,20.000000
mean,10.333333,1.220130e+06,73.666667,74.315789,79.529412,73.166667,272.750000,72.733333
std,5.816643,5.816643e+00,17.580069,15.836149,13.010177,17.426315,102.048681,48.017127
min,1.000000,1.220121e+06,34.000000,45.000000,50.000000,34.000000,0.000000,0.000000
25%,6.000000,1.220126e+06,64.750000,62.500000,70.000000,65.500000,216.250000,40.750000
50%,10.000000,1.220130e+06,77.500000,77.000000,80.000000,75.000000,304.000000,78.666667
75%,15.000000,1.220135e+06,85.500000,86.500000,90.000000,85.500000,349.500000,113.333333
max,20.000000,1.220140e+06,96.000000,96.000000,96.000000,96.000000,383.000000,127.666667

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 12 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   SNO      21 non-null     int64
 1   REGNO    21 non-null     int64
 2   NAME     20 non-null     object
 3   DOB      21 non-null     object
 4   GENDER   20 non-null     object
 5   ADDRESS  20 non-null     object
 6   M1       18 non-null     float64
 7   M2       19 non-null     float64
 8   M3       17 non-null     float64
 9   M4       18 non-null     float64
 10  TOTAL    16 non-null     float64
 11  AVG      20 non-null     float64
dtypes: float64(6), int64(2), object(4)
memory usage: 2.1+ KB

In [11]:
df.isnull()

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,True,True,False,True,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True,False,False,False,False,False
13,False,False,False,False,False,False,False,False,True,False,True,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,True,False,True,True,True,True,True,True,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,True,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,True,False,True,False
20,False,False,False,False,False,False,False,False,False,False,False,False

In [12]:
df.notnull()

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,True,True,True,True,True,True,True,True,True,False,False,False
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,False,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,False,False,True,False,True
10,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,True,True,True,True,True,True,True,True
12,True,True,True,True,True,True,False,True,True,True,True,True
13,True,True,True,True,True,True,True,True,False,True,False,True
14,True,True,True,True,True,True,True,True,True,True,True,True
15,True,True,False,True,False,False,False,False,False,False,True,True
16,True,True,True,True,True,True,True,True,True,True,True,True
17,True,True,True,True,True,True,True,True,True,False,True,True
18,True,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,False,True,False,True
20,True,True,True,True,True,True,True,True,True,True,True,True

In [13]:
df.dropna(axis=0) #remove the specif row

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [14]:
df.dropna(axis=1)  #remove the specif column

    SNO    REGNO         DOB
0     1  1220121  2000-02-10
1     2  1220122  1999-01-25
2     3  1220123  2000.09.21
3     4  1220124  2000-11-09
4     5  1220125  2000-11-21
5     6  1220126  1999-03-05
6     7  1220127  2000-10-02
7     7  1220127  2000-10-02
8     8  1220128  1999-01-25
9     9  1220129  2000.09.21
10   10  1220130  2000-11-09
11   11  1220131  2000-11-21
12   12  1220132  1999-03-05
13   13  1220133  2000-10-02
14   14  1220134    20001109
15   15  1220135    19990125
16   16  1220136    20000921
17   17  1220137    20001109
18   18  1220138    20001121
19   19  1220139    19990305
20   20  1220140    20001002

In [16]:
dfs = df[df['ADDRESS']=='THANDALAM']
dfs

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,NaN,NaN,NaN
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,NaN,59.0,60.0,70.0,NaN,0.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,NaN,68.0,70.0,70.0,208.0,69.333333
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,NaN,84.0,NaN,0.000000

In [ ]:
df.iloc[:4] #extract the specif rows

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa

In [17]:
df.iloc[0:4,1:4] #df.iloc[row,column]

     REGNO    NAME         DOB
0  1220121    ARUN  2000-02-10
1  1220122    BABU  1999-01-25
2  1220123  CHARAN  2000.09.21
3  1220124    DEVA  2000-11-09

In [ ]:
df.iloc[[1,12,35],[2,4]]

    petal_length species
1            1.4  setosa
12           1.4  setosa
35           1.2  setosa

In [18]:
df.fillna(0) #it will fill the missing value  ->0

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,0.0,0.0,0.000000
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,0.0,59.0,60.0,70.0,0.0,0.000000
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
9,9,1220129,INDRA,2000.09.21,FEMALE,KANCHIPURAM,64.0,0.0,0.0,64.0,0.0,0.000000
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,0.0,68.0,70.0,70.0,208.0,69.333333
13,13,1220133,MANI,2000-10-02,MALE,KANCHIPURAM,71.0,76.0,0.0,71.0,0.0,0.000000
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
15,15,1220135,0,19990125,0,0,0.0,0.0,0.0,0.0,0.0,0.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
17,17,1220137,RAGHU,20001109,MALE,POONAMALEE,67.0,64.0,70.0,0.0,201.0,67.000000
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,0.0,84.0,0.0,0.000000
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [3]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [19]:
df.fillna(method='ffill') #forward fill

/tmp/ipython-input-1943891123.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill') #forward fill

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,NaN,NaN,NaN
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,56.0,59.0,60.0,70.0,253.0,0.000000
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
9,9,1220129,INDRA,2000.09.21,FEMALE,KANCHIPURAM,64.0,96.0,90.0,64.0,376.0,0.000000
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,96.0,68.0,70.0,70.0,208.0,69.333333
13,13,1220133,MANI,2000-10-02,MALE,KANCHIPURAM,71.0,76.0,70.0,71.0,208.0,0.000000
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
15,15,1220135,NANI,19990125,MALE,POONAMALEE,79.0,77.0,80.0,79.0,0.0,0.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
17,17,1220137,RAGHU,20001109,MALE,POONAMALEE,67.0,64.0,70.0,86.0,201.0,67.000000
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,90.0,84.0,338.0,0.000000
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [20]:
df.fillna(method='bfill')

/tmp/ipython-input-3675081237.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
0,1,1220121,ARUN,2000-02-10,MALE,THANDALAM,82.0,81.0,90.0,56.0,253.0,84.333333
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
2,3,1220123,CHARAN,2000.09.21,MALE,THANDALAM,74.0,59.0,60.0,70.0,307.0,0.000000
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
9,9,1220129,INDRA,2000.09.21,FEMALE,KANCHIPURAM,64.0,45.0,50.0,64.0,163.0,0.000000
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
12,12,1220132,LATHESSH,1999-03-05,MALE,THANDALAM,71.0,68.0,70.0,70.0,208.0,69.333333
13,13,1220133,MANI,2000-10-02,MALE,KANCHIPURAM,71.0,76.0,80.0,71.0,315.0,0.000000
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
15,15,1220135,PRATHAP,19990125,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,0.0,0.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
17,17,1220137,RAGHU,20001109,MALE,POONAMALEE,67.0,64.0,70.0,81.0,201.0,67.000000
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
19,19,1220139,SARVESH,19990305,MALE,THANDALAM,84.0,87.0,80.0,84.0,301.0,0.000000
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333

In [21]:
df.dropna()

,SNO,REGNO,NAME,DOB,GENDER,ADDRESS,M1,M2,M3,M4,TOTAL,AVG
1,2,1220122,BABU,1999-01-25,MALE,KANCHIPURAM,56.0,61.0,80.0,56.0,253.0,84.333333
3,4,1220124,DEVA,2000-11-09,MALE,POONAMALEE,74.0,79.0,80.0,74.0,307.0,102.333333
4,5,1220125,ESTER,2000-11-21,FEMALE,CHITHUR,92.0,95.0,96.0,92.0,375.0,125.000000
5,6,1220126,FARHANA,1999-03-05,FEMALE,THANDALAM,91.0,88.0,90.0,91.0,360.0,120.000000
6,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
7,7,1220127,GANI,2000-10-02,MALE,KANCHIPURAM,49.0,51.0,70.0,49.0,219.0,73.000000
8,8,1220128,HEMA,1999-01-25,FEMALE,POONAMALEE,95.0,96.0,90.0,95.0,376.0,125.333333
10,10,1220130,JAHITH,2000-11-09,MALE,THANDALAM,34.0,45.0,50.0,34.0,163.0,54.333333
11,11,1220131,KANI,2000-11-21,FEMALE,CHITHUR,96.0,95.0,96.0,96.0,383.0,127.666667
14,14,1220134,NANI,20001109,MALE,POONAMALEE,79.0,77.0,80.0,79.0,315.0,105.000000
16,16,1220136,PRATHAP,20000921,MALE,KANCHIPURAM,86.0,84.0,90.0,86.0,346.0,115.333333
18,18,1220138,RATHI,20001121,FEMALE,KANCHIPURAM,81.0,86.0,90.0,81.0,338.0,112.666667
20,20,1220140,SANTHOSH,20001002,MALE,KANCHIPURAM,76.0,69.0,80.0,76.0,301.0,100.333333